### ISSUE TITLE
Premium For YouTube Music 

### ISSUE THREAD

**Issue by DrimTim2020** [inotia00/rvx-builder#61] opened 2023-02-26 16:24 UTC
[builder] INFO: Reading dex files
[builder] INFO: Loading resource table...
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] INFO: Loading resource table from file: .\revanced-cache\1.apk
[builder] INFO: Merging C:\rvx-builder-win 3.0.8\revanced\revanced-integrations-v0.99.5.apk
[builder] INFO: Skipping client-spoof-music: Manually excluded
[builder] INFO: Skipping custom-branding-music-afn-blue: Manually excluded
[builder] INFO: Skipping custom-branding-music-afn-red: Manually excluded
[builder] INFO: Skipping custom-branding-music-revancify: Manually excluded
[builder] INFO: Skipping enable-black-navbar: Manually excluded
[builder] INFO: Skipping enable-color-match-player: Manually excluded
[builder] INFO: Skipping enable-force-minimized-player: Manually excluded
[builder] INFO: Skipping enable-force-shuffle: Manually excluded
[builder] INFO: Skipping enable-opus-codec: Manually excluded
[builder] INFO: Skipping enable-tablet-mode: Manually excluded
[builder] INFO: Skipping hide-compact-header: Manually excluded
[builder] INFO: Skipping hide-music-cast-button: Manually excluded
[builder] INFO: Skipping hide-upgrade-button: Manually excluded
[builder] INFO: Skipping patch-options: Manually excluded
[builder] INFO: Loading resource table...
[builder] INFO: Deleting existing resource cache directory
[builder] SEVERE: Failed to delete existing resource cache directory
[builder] INFO: Decoding resources
[builder] INFO: Decoding AndroidManifest.xml with resources...
[builder] INFO: Loading resource table from file: .\revanced-cache\1.apk
[builder] INFO: Regular manifest package...
[builder] INFO: Decoding file-resources...
[builder] INFO: Decoding values */* XMLs...
[builder] INFO: background-play succeeded
[builder] INFO: enable-zen-mode succeeded
[builder] INFO: exclusive-audio-playback succeeded
[builder] java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:318) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:158) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: kotlin.UninitializedPropertyAccessException: lateinit property resourceMappings has not been initialized at app.revanced.patches.shared.patch.mapping.ResourceMappingPatch$Companion.getResourceMappings$revanced_patches(ResourceMappingPatch.kt:20) at app.revanced.patches.music.layout.premium.patch.HideGetPremiumPatch.(HideGetPremiumPatch.kt:40) ... 22 more

**It gets stuck on this and no further action.
But if you do not include the item ( Hide Premium Offers ) then everything works.**

**Comment by ILoveOpenSourceApplications** [comment] 2023-03-02 20:09
@inotia00 this can be closed as it's not a bug regarding the rvx builder.

**Closed** 2023-03-02 20:34 UTC
