### ISSUE TITLE
Youtube build error

### ISSUE THREAD

**Issue by meetaditya** [inotia00/rvx-builder#10] opened 2022-10-31 14:07 UTC
[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\F:\Programs\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:219:53)

OS : Windows 11

To reprodude : 

Building youtube on v3.14.16

**Comment by Spacellary** [comment] 2022-10-31 20:36
Hello! This is a duplicate of issue https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217, that I had and I did share the steps to solve that issue in this https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651. Please try that and report back in https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217 if you had success or even if didn't as this helps too.
#### For reference:
```
1) Uninstalled the Zulu JDK 17 version that was installed.
2) Uninstalled Node.js.
3) Installed Zulu JDK again (Zulu JDK 17 v17.36.15 from Winget).
4) Build again.
```

**Comment by meetaditya** [comment] 2022-11-01 09:44
Tried the steps as mentioned. Tried an upgraded version of Zulu JDK too, ends up with the same error.

**Comment by inotia00** [comment] 2022-11-01 13:12
duplicate https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651

**Closed by inotia00** 2022-11-01 13:12 UTC
