### ISSUE TITLE
bug: `integrations` patches are broken in Arabic environment

### ISSUE THREAD

**Issue by DaRandomCube** [inotia00/rvx-builder#66] opened 2023-03-07 08:43 UTC
**Describe the bug**
output
[log.txt](https://github.com/inotia00/rvx-builder/files/10961721/log.txt)

**To Reproduce**

1. patch youtube
2. see the error

**Screenshots**

**revanced-builder Version:** [e.g. v1.2.10]

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 home

**Additional context**

**Comment by inotia00** [comment] 2023-03-08 18:12
I tried to reproduce with the same patch options as indicated in the log, but could not reproduce.
Try simply reinstalling the builder

**Comment by orangeshroom** [comment] 2023-03-12 07:08
didn't work
maybe bitlocker?

**Comment by orangeshroom** [comment] 2023-03-12 07:26
nope
disabling bitlocke didn't work
I don't know if this is useful but my laptop language is arabic

**Comment by orangeshroom** [comment] 2023-03-13 14:04
It seems that the problem was in the language, when I changed the language to English I did not have any problem
(I apologize if my English is bad I use a translator)

**Comment by inotia00** [comment] 2023-03-13 14:27
This is a very strange and never reported issue.
what is your language?

**Comment by inotia00** [comment] 2023-10-02 11:35
fixed in [revanced-cli-v3.1.4](https://github.com/inotia00/revanced-cli/releases/tag/v3.1.4)

**Closed by inotia00** 2023-10-02 11:35 UTC
Labels: bug, good first issue
