### ISSUE TITLE
[builder] SEVERE: music-microg-support failed

### ISSUE THREAD

**Issue by ElissonRodrigues** [inotia00/rvx-builder#1] opened 2022-09-26 13:17 UTC
**LOG**
[builder] SEVERE: music-microg-support failed: app.revanced.patcher.patch.PatchResultError: 'music-microg-support' depends on 'music-microg-support' but the following error was raised: java.io.FileNotFoundException: ./revanced-cache/AndroidManifest.xml (No such file or directory)

**To Reproduce**
Select Youtube Music 

**revanced-builder Version:** 
Current

**Comment by inotia00** [comment] 2022-09-26 15:53
> **LOG** [builder] SEVERE: music-microg-support failed: app.revanced.patcher.patch.PatchResultError: 'music-microg-support' depends on 'music-microg-support' but the following error was raised: java.io.FileNotFoundException: ./revanced-cache/AndroidManifest.xml (No such file or directory)
> 
> **To Reproduce** Select Youtube Music
> 
> **revanced-builder Version:** Current

Update rvx-builder by entering the following command in termux

`./rvx-builder.sh update`

Then run rvx-builder again and try the patch again

And let me know if the issue is reproduced

There were no issues when I tested about 5 minutes ago.

**Comment by inotia00** [comment] 2022-09-26 17:29
This issue is fixed in [revanced-cli v2.12.2](https://github.com/inotia00/revanced-cli/releases/tag/v2.12.2)

**Closed** 2022-09-26 17:41 UTC
