### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by nobl55** [inotia00/rvx-builder#28] opened 2022-12-23 09:34 UTC
while building youtube revanced extended with v. 17.49.37 

An error occured:TypeError: Cannot read properties of undefined (reading 'replace')at outputName (/data/data/com.termux/files/home/rvx-builder/wsEvents/patchApp.js:94:35)at afterBuild (/data/data/com.termux/files/home/rvx-builder/wsEvents/patchApp.js:29:3)at Socket.

**Comment by nobl55** [comment] 2022-12-23 10:49
while patching i also get a warning aapt2 w unknown chunk type 200

i reinstalled everything including termux

**Comment by ryzen23** [comment] 2022-12-24 02:52
works fine on me try the build version on pc

**Comment by Spoderman1997** [comment] 2022-12-24 09:45
![1](https://user-images.githubusercontent.com/121338439/209430380-d67d3341-4f62-486e-9006-7f73ab30437b.png)

**Comment by Spacellary** [comment] 2022-12-25 12:54
For those having the issue, when you are able to, also try it with [reisxd's revanced builder](https://github.com/reisxd/revanced-builder) and check if it is also reproduced there. It may not be only a rvx-builder specific issue and would be useful to also raise the issue there, if reproduced of course, since that's what the rvx-builder is built from.

Also when possible if you can add your system information like what Android/OS version you're running as it may help them narrow it down a bit more for a fix if necessary.

<hr>

I also did a few tests, building Youtube and Youtube-Music in both reisxd's `revanced-builder-linux` and with `rvx-builder-linux` in **v3.7.0** and **I could not** experience this issue in a Linux environment running Ubuntu (WSL2), which I think is closest to what is being reported here.

###### System:  [Windows 11 22H2 (22621.963)](https://i.imgur.com/zNCMHEK.jpeg) <br> Environment: [Ubuntu 22.04.1 LTS (WSL2)](https://i.imgur.com/BYElmek.jpeg)

**Comment by dannymirxa** [comment] 2022-12-26 05:18
> ### Could to be related or the same thing as to [reisxd#615](https://github.com/reisxd/revanced-builder/issues/615) upstream.
> A fix ([reisxd@585c774](https://github.com/reisxd/revanced-builder/commit/585c7748d3d5a0498d07c4dbc5511fd34ccfe2a7)) was already implemented upstream and could be applied.
> 
> For those having the issue, when you are able to, also try it with [reisxd's revanced builder](https://github.com/reisxd/revanced-builder) and check if it is also reproduced there. It may not be only a rvx-builder specific issue and would be useful to also raise the issue there, if reproduced of course, since that's what the rvx-builder is built from.
> ###### PSA: `return-youtube-dislike` failling with reisxd's **revanced-builder** is a known issue, and was/is a problem with the official revanced-cli, it was fixed but a release wasn't pushed yet. It's not a problem with inotia00's builder since he compiled the fixed version (I think?) to be used with the RVX-builder. _Thank you, inotia00!_
> 
> Also when possible if you can add your system information like what Android/OS version you're running as it may help them narrow it down a bit more for a fix if necessary.
> 
> I also did a few tests, building Youtube and Youtube-Music in both reisxd's `revanced-builder-linux` and with `rvx-builder-linux` in **v3.7.0** and **I could not** experience this issue in a Linux environment running Ubuntu (WSL2), which I think is closest to what is being reported here.
> ###### System: [Windows 11 22H2 (22621.963)](https://i.imgur.com/zNCMHEK.jpeg)
> Environment: [Ubuntu 22.04.1 LTS (WSL2)](https://i.imgur.com/BYElmek.jpeg)

Tested in my phone, yes this solution works.

**Comment by Spacellary** [comment] 2022-12-27 10:27
For everyone using **Termux** it should be fixed now, can you guys try to update or reinstall and run again?

#### Update:
```
./rvx-builder.sh update && ./rvx-builder.sh run
```

##### Don't forget to backup your revanced.keystore if you plan on installing over your previous version.

#### Reinstall:
```
...
```

**Comment by Spacellary** [comment] 2022-12-30 02:42
@nobl55 @Spoderman1997 
Any changes/updates on the situation for you guys?

**Comment by Spacellary** [comment] 2023-01-03 06:44
Should be fixed now with **version 3.8.0**.

**Closed** 2023-02-18 15:45 UTC
