### ISSUE TITLE
rvx-builder failure

### ISSUE THREAD

**Issue by DomRico** [inotia00/rvx-builder#86] opened 2023-05-03 21:36 UTC
**Describe the bug**
Patching is done till the very end when it says Finished, it then changes to a Failure screen which i have attached a screenshot.
This has only started with rvx-builder v3.9.2 update.

**To Reproduce**

1. Start Patching after making all your selections
2. Wait for Patching to complete (no recorded errors during patching)
3. Patching completes with Finished shown
4. Then immediately it changes to failure screen (see attached screenshot)

**Screenshots**

**revanced-builder Version:** 
rvx-builder version 3.9.2

**Desktop (please complete the following information):**

- OS: Windows
- Version: 10

**Additional context**
![rvx-builder failure](https://user-images.githubusercontent.com/132504887/236053458-39088a69-221a-4829-8652-1096be39bda5.jpg)

**Comment by inotia00** [comment] 2023-05-04 02:29
duplicate of the following issue https://github.com/inotia00/rvx-builder/issues/84

**Closed by inotia00** 2023-05-04 02:29 UTC
