### ISSUE TITLE
v3.4.16 Youtube Build Error

### ISSUE THREAD

**Issue by lentm88** [inotia00/rvx-builder#9] opened 2022-10-31 13:37 UTC
**Describe the bug**

[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\ChrisB\Downloads\ReVanced\inotia00\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:219:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**To Reproduce**

I tried to build Youtube Revanced with v3.4.16, and got the error above. On v3.4.15, it builds fine.

**Screenshots**

**revanced-builder Version: v3.4.16

**Desktop (please complete the following information):**

- OS:  Windows
- Version: 10

**Additional context**
On v3.4.15, it builds fine.

**Comment by Spacellary** [comment] 2022-10-31 20:36
Hello! This is a duplicate of issue https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217, that I had and I did share the steps to solve that issue in this https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651. Please try that and report back in https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217 if you had success or even if didn't as this helps too.
#### For reference:
```
1) Uninstalled the Zulu JDK 17 version that was installed.
2) Uninstalled Node.js.
3) Installed Zulu JDK again (Zulu JDK 17 v17.36.15 from Winget).
4) Build again.
```

**Comment by inotia00** [comment] 2022-11-01 13:12
duplicate https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651

**Comment by lentm88** [comment] 2022-11-01 13:12
> Hello! This is a duplicate of issue [#7 (comment)](https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217), that I had and I did share the steps to solve that issue in this [#7 (comment)](https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651). Please try that and report back in [#7 (comment)](https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217) if you had success or even if didn't as this helps too.
> 
> #### For reference:
> ```
> 1) Uninstalled the Zulu JDK 17 version that was installed.
> 2) Uninstalled Node.js.
> 3) Installed Zulu JDK again (Zulu JDK 17 v17.36.15 from Winget).
> 4) Build again.
> ```

Thanks, Spacellary. I didn't have Node.js installed, so step 1&3 resolved the issue for me.

**Closed by inotia00** 2022-11-01 13:12 UTC
