### ISSUE TITLE
resource busy or locked, unlink '\\?\C:\Users\p

### ISSUE THREAD

**Issue by papppsanyi** [inotia00/rvx-builder#14] opened 2022-11-01 17:27 UTC
**Patching failed **
After the patching screen, error occures.
rvx-builder v3.4.16
Command prompt output
[builder] Listening at port 8000
[builder] The webserver is now running!
[builder] Opening the app in the default browser... Done, check if a browser window has opened
[builder] An error occured.
Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\myuser\Downloads\revanced-cache\1.apk'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    at rimrafSync (node:internal/fs/rimraf:195:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at rmSync (node:fs:1274:10)
    at afterBuild (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:38:3)
    at Socket.<anonymous> (C:\snapshot\rvx-builder-build3\wsEvents\patchApp.js:219:53)
[builder] Please report this bug here: https://github.com/inotia00/rvx-builder/issues.

**Desktop (please complete the following information):**

- OS: Win10 v22h2, os build 19045.2130

**Comment by papppsanyi** [comment] 2022-11-01 17:27
![image](https://user-images.githubusercontent.com/15232754/199298370-410ea1c6-274b-4051-8937-b04937c33790.png)

**Comment by Spacellary** [comment] 2022-11-01 17:46
Hello! This is a duplicate of issue https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217, and I did share the steps to solve that issue in this https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651. Please try that and report back in https://github.com/inotia00/rvx-builder/issues/7#issue-1428752217 if you had success or even if didn't as this helps too.
#### For reference:
I was able to now build normally after doing the following steps:

    1) Uninstalled the Zulu JDK 17 version that was installed.
    2) Uninstalled Node.js.

    3) Installed Zulu JDK again (Zulu JDK 17 v17.36.15 from Winget).
    4) Build again, with success.

I used [Geek Uninstaller](https://geekuninstaller.com/) to perform a clean removal (uninstall and remove residual files) of the software and I installed **Zulu JDK 17** v17.36.15 using [WingetUI](https://github.com/martinet101/WingetUI)/Winget.

**Comment by inotia00** [comment] 2022-11-02 07:36
duplicate https://github.com/inotia00/rvx-builder/issues/7#issuecomment-1296274651

**Closed by inotia00** 2022-11-02 07:36 UTC
